trigger:
  branches:
    include:
      - main
  paths:
    include:
      - OrderApi/*
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  imageName: order-api
  dockerFile: ./OrderApi/OrderApi/Dockerfile
  buildContext: ./OrderApi
 
stages:
  - stage: ImageBuild
    displayName: Build and push docker image
    jobs:
    - job: BuildImageAndPush
      displayName: Build and push docker image
      steps:
      - task: Docker@2
        displayName: Build and Push Docker Image
        inputs:
          buildContext: $(buildContext)
          command: buildAndPush
          Dockerfile: $(dockerFile)
          containerRegistry: 'shaijus-registry'
          repository: order-api
          tags: |
            $(Build.BuildId)
            latest
            

          
          